---
- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install mysql-server
  apt: 
    force_apt_get: yes
    update_cache: yes
    state: latest
    name:
      - mysql-server
      - mysql-client
      - python3-mysqldb

- name: Install python3-mysqldb
  apt:
    state: latest
    name:
      - python3-mysqldb


    

